# Generated by Django 5.2.6 on 2025-11-05 21:13

from django.db import migrations, models


def convert_habito_to_json(apps, schema_editor):
    Formulario = apps.get_model('api', 'Formulario')
    Habito = apps.get_model('api', 'Habito')
    
    for formulario in Formulario.objects.all():
        if formulario.habito_id:
            try:
                habito = Habito.objects.get(id=formulario.habito_id)
                formulario.habito_temp = {
                    'id': habito.id,
                    'nombre': habito.nombre,
                    'descripcion': getattr(habito, 'descripcion', '')
                }
                formulario.save(update_fields=['habito_temp'])
            except Habito.DoesNotExist:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_consumidor_genero'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='formulario',
            name='formularios_habito__6a6423_idx',
        ),
        migrations.AddField(
            model_name='formulario',
            name='habito_temp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(convert_habito_to_json, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='formulario',
            name='habito',
        ),
        migrations.RenameField(
            model_name='formulario',
            old_name='habito_temp',
            new_name='habito',
        ),
        migrations.AlterField(
            model_name='formulario',
            name='habito',
            field=models.JSONField(blank=True, help_text='Habit data as JSON (JSONB)', null=True),
        ),
    ]
