# Generated by Django 5.2.6 on 2025-11-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_formulario_formularios_habito__6a6423_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VwHeartRateToday',
            fields=[
                ('consumidor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total_ventanas', models.IntegerField()),
                ('ventanas_con_datos', models.IntegerField()),
                ('promedio_dia', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('minimo_dia', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('maximo_dia', models.DecimalField(decimal_places=1, max_digits=10, null=True)),
                ('ventanas', models.JSONField()),
            ],
            options={
                'verbose_name': 'Heart Rate Today',
                'verbose_name_plural': 'Heart Rate Today',
                'db_table': 'vw_heart_rate_today',
                'ordering': ['consumidor_id'],
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='vwdailysummary',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name': 'Daily Summary', 'verbose_name_plural': 'Daily Summary'},
        ),
        migrations.AlterModelOptions(
            name='vwdesiresstats',
            options={'managed': False, 'ordering': ['consumidor_id', 'deseo_tipo'], 'verbose_name': 'Desires Statistics', 'verbose_name_plural': 'Desires Statistics'},
        ),
        migrations.AlterModelOptions(
            name='vwdesirestracking',
            options={'managed': False, 'ordering': ['-fecha_creacion'], 'verbose_name': 'Desires Tracking', 'verbose_name_plural': 'Desires Tracking'},
        ),
        migrations.AlterModelOptions(
            name='vwhabitstats',
            options={'managed': False, 'ordering': ['consumidor_id'], 'verbose_name': 'Habit Statistics', 'verbose_name_plural': 'Habit Statistics'},
        ),
        migrations.AlterModelOptions(
            name='vwhabittracking',
            options={'managed': False, 'ordering': ['-fecha'], 'verbose_name': 'Habit Tracking', 'verbose_name_plural': 'Habit Tracking'},
        ),
        migrations.AlterModelOptions(
            name='vwheartratestats',
            options={'managed': False, 'ordering': ['consumidor_id'], 'verbose_name': 'Heart Rate Statistics', 'verbose_name_plural': 'Heart Rate Statistics'},
        ),
        migrations.AlterModelOptions(
            name='vwheartratetimeline',
            options={'managed': False, 'ordering': ['-fecha', '-hora'], 'verbose_name': 'Heart Rate Timeline', 'verbose_name_plural': 'Heart Rate Timeline'},
        ),
        migrations.AlterModelOptions(
            name='vwpredictionsummary',
            options={'managed': False, 'ordering': ['consumidor_id'], 'verbose_name': 'Prediction Summary', 'verbose_name_plural': 'Prediction Summary'},
        ),
        migrations.AlterModelOptions(
            name='vwpredictiontimeline',
            options={'managed': False, 'ordering': ['-fecha', '-hora'], 'verbose_name': 'Prediction Timeline', 'verbose_name_plural': 'Prediction Timeline'},
        ),
        migrations.AlterModelOptions(
            name='vwweeklycomparison',
            options={'managed': False, 'ordering': ['consumidor_id'], 'verbose_name': 'Weekly Comparison', 'verbose_name_plural': 'Weekly Comparison'},
        ),
    ]
